{
    "name": "Advance Odoo Chatter",
    "description": """Advance Odoo Chatter""",
    "summary": "Advance Odoo Chatter used to customize and beautify existing Odoo chatter",
    "category": "Web",
    'sequence': 30,
    "version": "16.0.1.0",
    "author": "Zehntech Technologies Pvt. Ltd.",
    "company": "Zehntech Technologies Pvt. Ltd.",
    "maintainer": "Zehntech Technologies Pvt. Ltd.",
    "contributor": "Zehntech Technologies Pvt. Ltd.",
    "website": "https://www.zehntech.com/",
    "support": "odoo-support@zehntech.com",
    "depends": [],
    "assets": {
        "web.assets_backend": [
            "advance_odoo_chatter/static/src/xml/chatter_topbar.xml",
            "advance_odoo_chatter/static/src/xml/follow_button.xml",
            "advance_odoo_chatter/static/src/scss/chatter_topbar.scss",
            "advance_odoo_chatter/static/src/js/chatter_topbar.js",
            "advance_odoo_chatter/static/src/js/chatter.js",
            "advance_odoo_chatter/static/src/js/form_renderer.js",
        ],
    },
    "data": [],
    "images": [
        "static/description/banner.gif",
    ],
    "license": "OPL-1",
    "installable": True,
    "application": False,
    "auto_install": False,
    "price": 75.00,
    "currency": "USD",
}
